env:
  es2020: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 11
  sourceType: module
  tsconfigRootDir: '.'
  project: ['./tsconfig.json']
plugins:
  - '@typescript-eslint'
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  prefer-const:
    - error
  prefer-arrow-callback:
    - error
  no-var:
    - error
  '@typescript-eslint/no-unused-vars':
    - error
    - varsIgnorePattern: "^_"
      argsIgnorePattern: "^_"
  '@typescript-eslint/no-empty-function': off
  # '@typescript-eslint/await-thenable':
  #   - error
overrides:
 - files:
     - "*.spec.ts"
   rules:
     '@typescript-eslint/no-unused-vars': off
     no-undef: off
     '@typescript-eslint/no-unsafe-return': off
     '@typescript-eslint/no-unsafe-member-access': off
     '@typescript-eslint/no-unsafe-call': off